### ISSUE TITLE
cannot build on latest nightly

### ISSUE THREAD

**Issue by NOBLES5E** [nkconnor/sharded#5]

**Comment by nkconnor** [comment]
thanks, should be fixed in https://github.com/nkconnor/sharded/commit/2788e5be6ed780b251816c9cdca6f75187c0ed0b

**Comment by NOBLES5E** [comment]
@nkconnor mind publishing a new release on crates.io?

**Comment by nkconnor** [comment]
Sure, tomorrow

**Comment by NOBLES5E** [comment]
Saw a new release. Closing
