### ISSUE TITLE
Release 0.3?

### ISSUE THREAD

**Issue by ChangeCaps** [nkconnor/sharded#7]
It seems the master branch hasn't seen updates in more than 6 months, maybe it's time to release version 0.3?

I in no way intend to be disrespectful, this should just be interpreted as a reminder if maybe this project hasn't been at the front of the maintainers mind for a little while.

**Comment by nkconnor** [comment]
I haven't looked at the project in a while, but, if I remember correctly there were some things I wanted to do before the next release. Was there something in particular you were looking forward to? You can always point to GitHub instead of crates.io to snag any commit, FYI.

**Comment by nkconnor** [comment]
v0.3 can be released when ready.. just let me know if you want to help! Thanks.
